modLoader="javafml"
loaderVersion="[4,)"
license="LGPL-3.0-or-later"
issueTrackerURL="https://github.com/Team-Arcadia/Arcadia-Spawn-Dimension/issues"

[[mods]]
modId="arcadia_spawn"
version="${mod_version}"
displayName="Arcadia Spawn"
authors="vyrriox, Team Arcadia"
description='''
Arcadia Spawn - Complete Spawn Dimension Management
Dynamic lobby menu, RTP, warmup/cooldown, LuckPerms meta overrides
Developed by Team Arcadia
'''

[[mixins]]
config="arcadia_spawn.mixins.json"

[[dependencies.arcadia_spawn]]
modId="neoforge"
type="required"
versionRange="[21.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.arcadia_spawn]]
modId="minecraft"
type="required"
versionRange="[1.21,1.22)"
ordering="NONE"
side="BOTH"

[[dependencies.arcadia_spawn]]
modId="arcadia_lib"
type="required"
versionRange="[1.2.0,)"
ordering="AFTER"
side="BOTH"
